name: MeckChat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter-test:
    name: Flutter App (Analyze, Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Flutter Platform Projects
        run: |
          cd apps/flutter
          flutter create --org com.meckchat --platforms=android,linux .
          rm -f test/widget_test.dart
          flutter pub get

      - name: Flutter Analyze
        run: |
          cd apps/flutter
          flutter analyze --no-fatal-infos

      - name: Flutter Unit Tests
        run: |
          cd apps/flutter
          flutter test --coverage
